title: R33ã®Tech Site
description: Tech save World
theme: architech
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
